### ISSUE TITLE
use math.isclose not == for float comparrisions

### ISSUE THREAD

**Issue by cleder** [cleder/pygeoif#100]
[The Right Way To Compare Floats in Python](https://davidamos.dev/the-right-way-to-compare-floats-in-python/)

**Comment by OscarSavolainen** [comment]
Hi, could I work on this issue? 

I presume the idea is to go through the codebase and replace all float comparison checks with math.isclose?

Thanks, it's my first open source contribution!

**Comment by cleder** [comment]
The `==` operator, or the `__eq__` method uses tuple equality to compare the coordinates. This should be done by comparing every coordinate with `math.isclose` instead. This would also allow comparing Lists and Tuples
