### ISSUE TITLE
Pip 23.1 deprecation warning

### ISSUE THREAD

**Issue by rez10191** [cleder/pygeoif#148]
Hello,

Thanks for all your work on this package.  

I've noticed that that when installing in a fresh virtual environment I get the following warning:

```
DEPRECATION: fxpmath is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
```

It looks like pip 23.1 is going to be released in the near future, so I thought I'd bring it to your attention.

Thanks again!

**Comment by cleder** [comment]
`fxpmath` is not a dependency of `pygeoif`, this is likely pulled in by another package
