### ISSUE TITLE
Add Hypothesis tests

### ISSUE THREAD

**Issue by cleder** [cleder/pygeoif#179]
- Add strategies to create [Point2D, Point3D, PointType and LineType](https://github.com/cleder/pygeoif/blob/develop/pygeoif/types.py) 
- Add Strategies to create [Geometries](https://github.com/cleder/pygeoif/blob/develop/pygeoif/geometry.py)

Test `pygeoif` against these strategies, `repr` and `geometry.wkt` are [Encode/Decode invariant](https://hypothesis.works/articles/encode-decode-invariant/)

The strategies should be similar to [hypothesis-geojson](https://github.com/mapbox/hypothesis-geojson/blob/master/hypothesis_geojson/__init__.py), but one should be able to create coordinates for any given [CRS (SRS)](https://en.wikipedia.org/wiki/Spatial_reference_system) with EPSG 4326 as a predefined shortcut

**Comment by bpshaver** [comment]
I'm interested in this issue. Is there a contribution guide? Should I work from the `develop` branch?

**Comment by cleder** [comment]
No guideline, sorry. Fork, and make your PR against `develop`

**Comment by cleder** [comment]
Commit often, commit early, make a draft PR while you are still working on it, so I can give you some pointers ;-)

**Comment by cleder** [comment]
After you cloned your fork, cd into the directory and
```
python3 -m venv .venv
source .venv/bin/activate
pip install '.[dev]'
pre-commit install
```

**Comment by bpshaver** [comment]
Sounds good. I'm more of a `pyenv` guy myself.

**Comment by cleder** [comment]
I am more of a minimalist :smile:

**Comment by bpshaver** [comment]
Draft PR here:

https://github.com/cleder/pygeoif/pull/186

I'm not super familiar with different spatial reference systems. Do you have in mind that these strategies would generate different values depending on the SRS provided?

**Comment by cleder** [comment]
Another approach may be using [hypothesis-jsonschema](https://github.com/python-jsonschema/hypothesis-jsonschema) and the [geo-json schema](https://github.com/geojson/schema/tree/main/src/schema)

**Comment by cleder** [comment]
Are you still working on this, or did you loose interest?

**Comment by bpshaver** [comment]
Didn't lose interest, just lost time. I will budget time for this tomorrow.
