### ISSUE TITLE
Add force_2d and force_3d

### ISSUE THREAD

**Issue by cleder** [cleder/pygeoif#180]
Add functions [force_2d](https://shapely.readthedocs.io/en/stable/reference/shapely.force_2d.html) and [force_3d](https://shapely.readthedocs.io/en/stable/reference/shapely.force_2d.html) to `factories.py`

**Comment by whisk** [comment]
Hi @cleder , please check my PR #183 which adds `force_2d` for some geometries to see if that's what you are expecting, before I go to far with `force_3d` :)

**Comment by whisk** [comment]
I accidentally broke PR #183, the new code is in #185
